# Generated by Django 5.2.7 on 2026-06-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_id'),
        ('accounts', '0002_studentprofile_resume'),
    ]

    operations = [
    ]
