# Generated by Django 5.2.7 on 2026-06-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_studyquestion_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('company', 'Company-Specific')], default='technical', max_length=20)),
                ('question_text', models.TextField(help_text='e.g., What is the virtual DOM in React?')),
                ('answer_text', models.TextField(help_text='Detailed explanation for the student to read.')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_questions', to='assessment.company')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_questions', to='assessment.subject')),
            ],
        ),
    ]
