# Generated by Django 5.2.7 on 2026-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_learnedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=20, null=True),
        ),
    ]
