# Generated by Django 6.0.6 on 2026-06-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_alter_assessment_id_alter_assessmentresult_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyTopic',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='passing_marks',
            field=models.PositiveIntegerField(default=50, help_text='Minimum score to pass'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_marks',
            field=models.PositiveIntegerField(default=100, help_text='Total possible score'),
        ),
        migrations.AlterField(
            model_name='learnedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_by_students', to='assessment.learningquestion'),
        ),
        migrations.AlterField(
            model_name='learningquestion',
            name='answer_text',
            field=models.TextField(blank=True, help_text='Detailed explanation for the student.', null=True),
        ),
    ]
